// packages
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:flutter_local_notifications/flutter_local_notifications.dart';
export 'package:fluttertoast/fluttertoast.dart';

// files
export 'package:flutter/material.dart';
export 'package:todo/app.dart';
export 'package:todo/routes/route_names.dart';
export 'package:todo/routes/app_routes.dart';
export 'services/notification_service.dart';
export 'package:todo/utils/assets.dart';
export 'package:todo/utils/app_colors.dart';
export 'package:todo/views/1_splash/splash_view.dart';
export 'package:todo/views/2_home/home_view.dart';
export 'package:todo/views/2_home/components/no_task.dart';
export 'package:todo/views/3_tasks/tasks_view.dart';
export 'package:todo/views/full_view.dart';
export 'package:todo/widgets/buttons/circle_button.dart';
export 'package:todo/widgets/buttons/addtask_button.dart';
export 'package:todo/utils/rubik_font.dart';
export 'package:todo/views/1_splash/components/green_button.dart';
export 'package:todo/widgets/custom_appbar.dart';
export 'package:todo/widgets/bottom_paint.dart';
export 'package:todo/models/category_model.dart';
export 'package:todo/views/4_addtask/components/category_list_item.dart';
export 'package:todo/views/4_addtask/components/custom_textfield.dart';
export 'package:todo/widgets/buttons/simple_button.dart';
export 'package:todo/utils/date_time_utils.dart';
export 'package:todo/utils/message_utils.dart';
